### ISSUE TITLE
How do I use this plugin? What does Audience means?

### ISSUE THREAD

**Issue by EAdeveloper** [VirtusLab/strapi-plugin-navigation#22]
Thank you for creating this plugin. I need some help understanding it.
@strapi 🚀
![image](https://user-images.githubusercontent.com/21114220/101204990-164c4680-363b-11eb-8142-381d88561ae5.png)

**Comment by cyp3rius** [comment]
Hi @EAdeveloper, to manage the navigation structure like `Navigation` & `NavigationItems`, you've to use delivered Plugin UI -> `UI Navigation`. Those Collections are not manageable and should be hidden from Content Manager point of view because of additional constraints and checks delivered by dedicated UI. 

There is already a Strapi core PR to handle this: https://github.com/strapi/strapi/pull/6955

With `Audiences` you can used Content Manager without any restrictions. Those are just simple content types (line name, key etc) that defines an audience. For example:

- Public
- Private
- Staff only

If you configure such Audiences, you might use them while defining the navigation structure using UI Navigation and consume in your Front-end app. That's mainly all.

**Comment by EAdeveloper** [comment]
> Hi @EAdeveloper, to manage the navigation structure like `Navigation` & `NavigationItems`, you've to use delivered Plugin UI -> `UI Navigation`. Those Collections are not manageable and should be hidden from Content Manager point of view because of additional constraints and checks delivered by dedicated UI.
> 
> There is already a Strapi core PR to handle this: [strapi/strapi#6955](https://github.com/strapi/strapi/pull/6955)
> 
> With `Audiences` you can used Content Manager without any restrictions. Those are just simple content types (line name, key etc) that defines an audience. For example:
> 
> * Public
> * Private
> * Staff only
> 
> If you configure such Audiences, you might use them while defining the navigation structure using UI Navigation and consume in your Front-end app. That's mainly all.

I understand now, thank you.
I also created a gatsby source plugin to fetch the Navigations since it is not expose by the current gatsby-source-strapi plugin.
